quarkus:
  log:
    min-level: DEBUG
    console:
      enable: true
      format: "[%-5p] %d{yyyy-MM-dd HH:mm:ss.SSS} [%c{2.}] %c{1} - %m%n"
      level: DEBUG

  # Swagger-UI
  swagger-ui:
    always-include: true

influxdb:
  connectionUrl: https://us-central1-1.gcp.cloud2.influxdata.com/
  token: token
  orgId: orgId
  data:
    bucketId: bucketId
    bucketName: ParticleDevice
